baseurl = "https://benetis.me/"
languageCode = "en-us"
Title = "Typical personal blog"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; All rights reserved"
canonifyurls = true

[menu]
    [[menu.main]]
    identifier = "angular"
    name       = "Angular"
    url        = "/angular"
    weight     = 4

    [[menu.main]]
    identifier = "functional"
    name       = "Functional programming and math"
    url        = "/functional_and_math/"
    weight     = 5

    # [[menu.main]]
    # identifier = "artificial_intelligence"
    # name       = "Machine learning"
    # url        = "/artificial_intelligence/"
    # weight     = 1

    [[menu.main]]
    identifier = "frontend"
    name       = "Web, Frontend and Client side"
    url        = "/fronend_web/"
    weight     = 5

    [[menu.main]]
    identifier = "human_things"
    name       = "Self development & other human things"
    url        = "/self-development-human-things/"
    weight     = 5

    [[menu.main]]
    identifier = "algorithms_pet_projects"
    name       = "Other algorithms, exercises and pet projects"
    url        = "/algorithms_pet_projects/"
    weight     = 6

[params]
  paginate = 5
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "benetisz"
  # facebook = "Your Facebook username"
  # instagram = "Your Instagram username"
  # googleplus = "Your Google+ account URL" # https://plus.google.com/u/0/xxxxxx
  github = "benetis"
  # npm = "Your npm username"
  # codepen = "Your CodePen username"
  # dribbble = "Your Dribbble username"
  # fivehundredpx = "Your 500px username" # 500px
  # flickr = "Your Flickr username"
  # pinterest = "Your Pinterest username"
  # tumblr = "Your Tumblr username"
  # vimeo = "Your Vimeo username"
  # youtube = "Your YouTube username"
  linkedin = "benetis"
  # Disqus shortname
  # disqus = ""
  # Google Analytics API key.
  ga_api_key = "UA-36419336-4"
  author = "Žygimantas Benetis (Zygimantas Benetis)"
  # authorwebsite = "example.com"
  # avatar = "/path/to/avatar"
  contact = "https://benetis.me/posts/contact-me/"
  bio = "Software engineer - Functional - Frontend - Scala - ML"
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Thoughts on us, humans and software"
  # Logo image. This is displayed ogp image.
  # logo = "/path/to/logo"
  # favicon = "/path/to/favicon"
