baseurl = "https://benetis.me/"
languageCode = "en-us"
Title = "Typical personal blog"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright notice"

[params]
  paginate = 5
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  # twitter = "Your Twitter username"
  # facebook = "Your Facebook username"
  # instagram = "Your Instagram username"
  # googleplus = "Your Google+ account URL" # https://plus.google.com/u/0/xxxxxx
  # github = "Your GitHub username"
  # npm = "Your npm username"
  # codepen = "Your CodePen username"
  # dribbble = "Your Dribbble username"
  # fivehundredpx = "Your 500px username" # 500px
  # flickr = "Your Flickr username"
  # pinterest = "Your Pinterest username"
  # tumblr = "Your Tumblr username"
  # vimeo = "Your Vimeo username"
  # youtube = "Your YouTube username"
  # linkedin = "Your LinkedIn username"
  # Disqus shortname
  # disqus = ""
  # Google Analytics API key.
  # ga_api_key = "Your Google Analytics tracking id"
  # author = "Your Name"
  # authorwebsite = "example.com"
  # avatar = "/path/to/avatar"
  contact = "https://benetis.me/posts/contact-me/"
  # bio = "Your short bio"
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Thoughts on us, humans and software"
  # Logo image. This is displayed ogp image.
  # logo = "/path/to/logo"
  # favicon = "/path/to/favicon"
